### PR TITLE
Bug 1333826 - Stop shipping the Firefox SDK on all platforms

### PR DESCRIPTION
**Pull request by bsmedberg**
r? @lundjordan

### CODE REVIEW

**Comment by lundjordan** [comment]
@bsmedberg fyi, we will have to remove the following lines on both mozilla-central and mozilla-aurora prior to merging this patch: https://dxr.mozilla.org/mozilla-central/source/taskcluster/taskgraph/transforms/beetmover.py#94,97

It's unfortunate for now but mach taskgraph is the source of truth for files, this patch here is simply the mapping dict. In the future we hope to only have to define the list of upload artifacts in one place, at the build sys level: https://bugzilla.mozilla.org/show_bug.cgi?id=1331143

**Comment by bsmedberg** [comment]
Yes, that's the patch at https://bugzilla.mozilla.org/attachment.cgi?id=8830460

**Comment by MihaiTabara** [comment]
@lundjordan @bsmedberg 
If this is not urgent, I can take this change and add it under https://github.com/mozilla-releng/beetmoverscript/pull/32/ which will make a larger change with respect to generating checksums.

**Comment by MihaiTabara** [comment]
@lundjordan @bsmedberg
I've included your change in the PR I'm about to land. Please double check here - https://github.com/mozilla-releng/beetmoverscript/blob/master/beetmoverscript/templates/firefox_nightly.yml.

Feel free to close the PR after that. Thanks and sorry for hijacking the change! ^_^

**Comment by MihaiTabara** [comment]
Nevermind me, I added back the SDK files as I didn't want to land the other patches to aurora + nightly without r?.

**Comment by MihaiTabara** [comment]
Did a manual merge. Thanks for patching this!

**Pull request merged**
