### PR TITLE
Production push doc update

### PR DESCRIPTION
**Pull request by nthomas-mozilla**
* process changes for puppet move to github
* move of puppet repo into mozilla-releng org
* add note to wait for masters to sync requirements.txt change

### CODE REVIEW

**Comment by tomprince** [comment]
This should have a newsfragement.

**Comment by MihaiTabara** [comment]
Come to think about it after chatting with @nthomas-mozilla - this raises the question, some of the PRs are not quliafiying for a bug number, hence am not sure they should really have a newsfragment. I mean, any code change that can affect functionality should have a bug number I suppose, but for doc fixing or tooling (e.g. `tox`, `coveralls`, etc) I don't think it's worth filing a bug. 

@tomprince what do you think?

**Comment by MihaiTabara** [comment]
Let's make a consensus: any changes that don't have a tracking bug number in Bugzilla can ignore the newsfragment I suppose. In this category we can definitely shove the update of the info files (README, requirements, etc). We can always come back and change this.

**Comment by MihaiTabara** [comment]
Pushing this to be grabbed in the upcoming 7.5.0 roll-out

**Pull request merged**
